### ISSUE TITLE
postFetchFilterTest issue results in a didChangeSection with NSNotFound

### ISSUE THREAD

**Issue by malhal** [blindingskies/BSFetchedResultsController#3] opened 2015-05-02 14:20 UTC
If you have a predicate that has results but a postFetchFilterTest that removes them all, and then save a new managed object that does match the filter test, it crashes. It appears to be an issue with how the sections handle no objects, possibly the sorted section logic, it ends up calling didChangeSection with an NSNotFound sectionIndex.

```
WiFiFoFum-Passwords[29459:8411491] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayI objectAtIndex:]: index 9223372036854775807 beyond bounds for empty array'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010dc57c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010d262bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010db4e17e -[__NSArrayI objectAtIndex:] + 190
	3   WiFiFoFum-Passwords                 0x000000010cc66d13 -[BSFetchedResultsController updateObjects:] + 1571
	4   WiFiFoFum-Passwords                 0x000000010cc63f04 __58-[BSFetchedResultsController registerNotificationHandlers]_block_invoke + 772
	5   Foundation                          0x000000010cdd53b1 -[__NSObserver _doit:] + 291
	6   CoreFoundation                      0x000000010dc2754c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	7   CoreFoundation                      0x000000010db25a04 _CFXNotificationPost + 2484
	8   Foundation                          0x000000010cdb8968 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	9   CoreData                            0x000000010d55babe -[NSManagedObjectContext(_NSInternalChangeProcessing) _createAndPostChangeNotification:withDeletions:withUpdates:withRefreshes:] + 334
	10  CoreData                            0x000000010d4ca791 -[NSManagedObjectContext(_NSInternalChangeProcessing) _processRecentChanges:] + 2897
	11  CoreData                            0x000000010d4ce0f3 -[NSManagedObjectContext save:] + 131
```

**Comment by danthorpe** [comment] 2015-05-03 21:25
Hey @malcolmhall. Thanks for the info, I'll try to have a look into this for you. Can't promise I'll be able to fix it though - it's a pretty old project. If you have a fix, feel free to submit a PR :)

**Comment by malcolmhall** [comment] 2015-05-07 18:52
Hi @danthorpe, it was tough to fix, I have a work around but not sure its right. There appears to be two cases where it crashes. When the fetch initially has no objects and then one is added that matches the post fetch filter. And also when the fetch initially has objects but none match the post fetch filter, and then one is added that matches the filter. Both problems stem from the updateObjects method.

For the first case, line 1032 the atIndex:[_sortedSectionNames indexOfObject:aSection.key]  has NSNotFound which causes the table update to crash. This is because the _sortedSectionNames created at 1731 uses self.sections and since none of the sections match the objectsPassingTest at 773 it doesn't add the default section key. Maybe 1032 needs the same checks on the section index that the 1051 & 1074 etc.

For the second case, 1398 causes an index out of range exception because 1391 returns an NSIndexPath with a section of NSNotFound. I fixed by changing 694 and 701 to:

694:
   
    // If there isn't a section key path, use the default key
    if(_sectionNameKeyPath) {
        key = [object valueForKeyPath:_sectionNameKeyPath];
    } else {
        key = kBSFetchedResultsControllerDefaultSectionName;
        sectionIndex = 0;
    }

701:

    // The section index
    if([_sortedSectionNames containsObject:key]){
        sectionIndex = [_sortedSectionNames indexOfObject:key];
    }

Then at 1396 this prevents the crash:

            // Get the old section key
            BSFetchedResultsControllerSection *oldSection = nil;
            NSString *oldKey = nil;
            if(_sortedSectionNames.count){
                oldKey = [_sortedSectionNames objectAtIndex:indexPath.section];
            }

Since you know the design better than me I bet if you take a look you'll notice the bugs that cause this to happen and can probably fix it better than my patch work.

**Comment by danthorpe** [comment] 2015-05-08 11:42
Hi @malcolmhall can you re-try your scenario using branch `BSFRC-3_adding_items_which_are_filtered` - I think I've fixed the underlying issue you're bumping into.

**Comment by malcolmhall** [comment] 2015-05-09 02:25
Hi @danthorpe I tried my scenario with BSFRC-3 and I'm afraid it crashes on line 1402:

    NSString *oldKey = [_sortedSectionNames objectAtIndex:indexPath.section];


    *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 9223372036854775807 beyond bounds for empty array'

**Comment by malcolmhall** [comment] 2015-05-13 16:51
Hi @danthorpe I've came across another problem in testing my app. If you delete the last row which causes the default section to be deleted, if you add a row again it doesn't add the section again however it does call the table delegate to insert the section, so it crashes because number of sections is incorrect. The issue is within the "we have an object which was filtered and now isn't filtered I've come up with a fix at line 1475 where it adds the new row:

            } else if (wasFiltered && !isFiltered) {
                
                // So here, we have an object which was filtered and now isn't filtered
                
                // Check to see if the object has changed sections
                if (![oldKey isEqualToString:key]) {
                    
                    // So, the section has also changed, which means that we need to remove
                    // the object from the old section's filtered objects
                    [oldSection removeFilteredObject:obj];
                    
                    // MALC fix to insert section if doesn't exist
                    if ([section.objects count] == 0) {
                        [insertedSections addObject:section];
                        section.isDisplayed = YES;
                    }
                    
                    // Add the object to the section's objects
                    [section addObject:obj];

**Closed** 2016-01-04 16:44 UTC
